apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucca-chatbackend-application
spec:
  replicas: 2
  selector:
      matchLabels:
        app: lucca-chatbackend-application
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: lucca-chatbackend-application
    spec:     # pod spec                  
      containers: 
      - name: lucca-backend-image
        image: us.icr.io/luccaspace/lucca-backend-image:latest # image we pushed
        ports:
          - containerPort: 8080
        env:
          - name: APIKEY
            value: w9kKE7rI4Jj_sStPwsAwbKGEp_ResyAWZknES0Je7yfs
          - name: URL
            value: https://gateway-wdc.watsonplatform.net/assistant/api
          - name: ASSISTANT_ID
            value: 92994250-973c-462b-b084-32f1829cb4e7